export const pollStrings = {
  title: 'Poll',
  noPollCreated: 'No Poll Created',
  startGathering: 'Start Gathering Opinions and Insights',
  createPoll: 'Create Poll',
  active: 'Active',
  past: 'Past',
  pollEndsOn: 'Poll ends on',
  pollEndsIn: 'Poll ends in',
  pollExpired: 'Poll expired',
  closedOn: 'Closed on',
  yourVote: 'Your vote',
  vote: 'VOTE',
  viewVotes: 'VIEW VOTES',
  minAgo: 'min',
  hrAgo: 'hr',
  dayAgo: 'day',
  createPollTitle: 'Create Poll',
  editPollTitle: 'Edit Poll',
  loadingPollData: 'Loading poll data...',
  errorLoadingPollData: 'Error loading poll data',
  questionLabel: 'Question*',
  questionPlaceholder: 'Type your question here',
  answerOptionsLabel: 'Answer options* (at least 2 options)',
  optionPlaceholder: 'Option',
  addOption: 'Add Option',
  closePollLabel: 'Close poll on*',
  allowMultipleAnswers: 'Allow multiple answers',
  reminders: 'Reminders',
  reminderOptions: 'Select reminder times:',
  reminderOptionList: [
    { value: '5', label: '5 minutes before' },
    { value: '15', label: '15 minutes before' },
    { value: '30', label: '30 minutes before' },
    { value: '60', label: '1 hour before' },
  ],
  saveButtonTitle: 'Save',
  createPollButtonTitle: 'Create Poll',
  pollCreated: 'Poll Created',
  pollCreationFailed: 'Failed to create poll. Please try again.',
  validationError: 'Validation Error',
  pleaseEnterAQuestionForYourPoll: 'Please enter a question for your poll.',
  pleaseProvideAtLeast2AnswerOptions: 'Please provide at least 2 answer options.',
  pleaseSelectAClosePollDateIsNotGreaterThanTripEndDate: 'Please select a close poll date is not greater than trip end date.',
  pollUpdatedSuccessfully: 'Poll updated successfully',
  pollUpdatedTitle: 'Poll Updated',
  pollDetailTitle: 'Poll Detail',
  singleSelect: 'Single select',
  multipleSelect: 'Multiple select',
  viewVotesDetail: 'View Votes',
  viewPollResults: 'View Results',
  submit: 'Submit',
  errorLoadingDetail: 'Error loading poll details',
  voteSubmittedSuccessfully: 'Vote submitted successfully',
  voteSubmittedTitle: 'Vote Submitted',
  viewVotesTitle: 'View Votes',
  tripMembersVoted: 'of',
  votes: 'votes',
  voteSingular: 'vote',
  shareResult: 'Share Result with Team Members',
  activeVotes: 'Active',
  closedVotes: 'Closed',
  loadingVotes: 'Loading poll votes...',
  errorLoadingVotes: 'Error loading poll votes',
  pollPublishedSuccessfully: 'Poll published successfully',
  pollPublishedTitle: 'Poll Published',
};
