export const strings = {
  title: 'Edit Profile',
  saveButton: 'Save Changes',
  firstName: 'First Name',
  firstNamePlaceholder: 'Enter your first name',
  lastName: 'Last Name',
  lastNamePlaceholder: 'Enter your last name',
  preferredName: 'Preferred Name',
  preferredNamePlaceholder: 'Enter your preferred name',
  pronouns: 'Pronouns',
  pronounsPlaceholder: 'Select your pronouns',
  country: 'Country',
  countryPlaceholder: 'Select your country',
  state: 'State',
  statePlaceholder: 'Select your state',
  postalCode: 'Postal Code',
  postalCodePlaceholder: 'Enter your postal code',
  preferredAirport: 'Preferred Airport',
  preferredAirportPlaceholder: 'Select your preferred airport',
  profileUpdateSuccessTitle: 'Success',
  profileUpdateSuccessMessage: 'Profile updated successfully',
  profileUpdateErrorTitle: 'Error',
  profileUpdateErrorMessage: 'Failed to update profile. Please try again.',
};
