export const mealStrings = {
  noMealAdded: 'No Meal Added',
  onceAdded: 'Once added, All traveler meals will be visible',
  addMealTitle: 'Add a Meal',
  editMealTitle: 'Edit a Meal',
  loadingMealData: 'Loading meal data...',
  errorLoadingMealData: 'Error loading meal data',
  mealDateLabel: 'Meal Date',
  mealDatePlaceholder: 'Date',
  selectMealTypeLabel: 'Select Meal Type',
  selectMealTypePlaceholder: 'Please select meal',
  deadlineDateLabel: 'Order deadline Date',
  deadlineDatePlaceholder: 'Select date',
  deadlineTimeLabel: 'Order deadline Time',
  deadlineTimePlaceholder: 'Select time',
  addRestaurantLabel: 'Add restaurant',
  restaurantNamePlaceholder: 'Enter restaurant name',
  foodMenuLinkPlaceholder: 'Enter food menu link',
  addAdditionalRestaurant: 'Add additional restaurant',
  addButton: 'Add',
  saveButton: 'Save',
  validationError: 'Validation Error',
  mealDateRequired: 'Meal Date is required',
  mealTypeRequired: 'Select Meal Type is required',
  deadlineDateRequired: 'Deadline Date is required',
  deadlineTimeRequired: 'Deadline Time is required',
  deadlineDateTimeRequired: 'Order deadline date time cannot be after meal date',
  deadlineDateTimeCannotBeAfterTripEndDate: 'Order deadline date time cannot be after trip end date',
  restaurantRequired: 'At least one restaurant is required',
  restaurantNameRequired: 'Restaurant name is required',
  reminders: 'Reminders',
  reminderOptions: 'Select reminder times:',
  reminderOptionList: [
    { value: '5', label: '5 minutes before' },
    { value: '15', label: '15 minutes before' },
    { value: '30', label: '30 minutes before' },
    { value: '60', label: '1 hour before' },
  ],
  mealUpdatedTitle: 'Meal Updated',
  mealUpdatedSuccessfully: 'Meal updated successfully',
  // Common strings
  loading: 'Loading...',
  error: 'Error',
  cancel: 'Cancel',
  submit: 'Submit',
  update: 'Update',
  edit: 'Edit',
  delete: 'Delete',
  open: 'Open',
  closed: 'Closed',
  today: 'Today',
  user: 'User',
  other: 'Other',
  // MealOrderDetail strings
  errorLoadingMealDetails: 'Error loading meal details',
  orderDeadline: 'Order Deadline :',
  orderSummary: 'Order Summary',
  collected: 'Collected',
  pending: 'Pending',
  hostText: 'Host',
  noMealSpecified: 'No meal specified',
  noRestaurantSpecified: 'No restaurant specified',
  noCollectedOrdersYet: 'No collected orders yet',
  noPendingOrders: 'No pending orders',
  submitYourMeal: 'Submit Your Meal',
  editYourMeal: 'Edit Your Meal',
  foodOrder: 'Food Order',
  foodOrderPlaceholder: 'Please enter exact food order here',
  pleaseEnterFoodOrder: 'Please enter your food order',
  orderClosed: 'Order Closed',
  cannotSubmitAfterDeadline: 'Cannot submit order after deadline',
  orderUpdated: 'Order Updated',
  orderUpdatedSuccessfully: 'Your meal order has been updated successfully',
  mealSubmitted: 'Meal Submitted',
  mealSubmittedSuccessfully: 'Your meal order has been submitted successfully',
  failedToUpdateOrder: 'Failed to update meal order. Please try again.',
  failedToSubmitOrder: 'Failed to submit meal order. Please try again.',
  updateFailed: 'Update Failed',
  submissionFailed: 'Submission Failed',
  // SubmitMeal strings
  selectRestaurant: 'Select restaurant',
  selectRestaurantPlaceholder: 'Select restaurant',
  mealInformationNotAvailable: 'Meal information not available',
  // MealDetail strings
  noMealsFoundForDate: 'No meals found for this date',
  addAMeal: 'Add a Meal',
  mealDeleted: 'Meal Deleted',
  mealDeletedSuccessfully: 'Meal deleted successfully',
  deleteFailed: 'Delete Failed',
  failedToDeleteMeal: 'Failed to delete meal. Please try again.',
  areYouSure: 'Are you sure ?',
  deleteMealConfirmation: 'Are you sure you want to delete this meal ? This action cannot be undone.',
  deleteAMeal: 'Delete a Meal',
  // MealDetailCard strings
  orderDeadlineLabel: 'Order Deadline :',
  yourOrder: 'Your Order :',
  pleaseSubmitYourOrder: 'Please submit your order',
  orderCollected: 'Order Collected :',
  pendingLabel: 'Pending :',
  // ManageFoodOrder strings
  manageFoodOrder: 'Manage Food Order',
  // MealCard strings
  todayLabel: 'Today',
  // AddMeal strings
  success: 'Success',
  mealAddedSuccessfully: 'Meal added successfully',
  somethingWentWrong: 'Something went wrong',
  userIdRequired: 'User ID is required',
};

export const MEAL_TYPES = [
  { label: 'Breakfast', value: 'breakfast' },
  { label: 'Lunch', value: 'lunch' },
  { label: 'Dinner', value: 'dinner' },
  { label: 'Pre Game', value: 'pre-game' },
  { label: 'Post Game Dinner', value: 'post-game-dinner' },
  { label: 'Snack', value: 'snack' },
];
