export const tripDetailsStrings = {
  errorMessage: 'Unable to load trip details. Please try again.',
  noCoverImage: 'No Cover Image',
  groupTrip: 'Group Trip',
  addTripMembers: 'Add Trip Members',
  itinerary: 'Itinerary',
  youAreOwner: 'You are the Owner!',
  travel: 'Travel',
  lodging: 'Lodging',
  activity: 'Activity',
  importItinerary: 'Import Itinerary',
  tripFeatures: 'Trip Features',
  announcement: 'Announcement',
  chat: 'Chat',
  manageFoodOrder: 'Manage Food Order',
  tripMembers: 'Trip Members',
  poll: 'Poll',
  map: 'Map',
  editTrip: 'Edit Trip',
  editComingSoon: 'Edit functionality coming soon',
  importComingSoon: 'Import functionality coming soon',
  featureComingSoon: 'functionality coming soon',
  addComingSoon: 'Add functionality coming soon',
}; 