export const tripDetailsStrings = {
  errorMessage: 'Unable to load trip details. Please try again.',
  noCoverImage: 'No Cover Image',
  groupTrip: 'Group Trip',
  addTripMembers: 'Add Trip Members',
  itinerary: 'Itinerary',
  youAreOwner: 'You are the Owner!',
  travel: 'Travel',
  lodging: 'Lodging',
  activity: 'Activity',
  importItinerary: 'Import Itinerary',
  tripFeatures: 'Trip Features',
  announcement: 'Announcement',
  chat: 'Chat',
  manageFoodOrder: 'Manage Food Order',
  tripMembers: 'Trip Members',
  poll: 'Poll',
  map: 'Map',
  editTrip: 'Edit Trip',
  deleteTrip: 'Delete Trip',
  deleteTripTitle: 'Delete Trip',
  deleteTripMessage:
    'Are you sure you want to delete this trip? This action cannot be undone.',
  deleteTripSuccess: 'Trip deleted successfully',
  deleteTripError: 'Failed to delete trip. Please try again.',
  editComingSoon: 'Edit functionality coming soon',
  importComingSoon: 'Import functionality coming soon',
  featureComingSoon: 'functionality coming soon',
  addComingSoon: 'Add functionality coming soon',
  exitTrip: 'Exit Trip',
  exitTripSuccess: 'You have successfully exited the trip',
  exitTripError: 'Failed to exit trip. Please try again.',
  userIdNotFound: 'User ID not found. Please try again.',
  success: 'Success',
  error: 'Error',
};
