export const strings = {
  title: "Let's get to know you.",
  step1: '1 of 2',
  step2: '2 of 2',
  firstName: 'First name*',
  firstNamePlaceholder: 'Enter first name',
  lastName: 'Last name*',
  lastNamePlaceholder: 'Enter last name',
  preferredName: 'Preferred name*',
  preferredNamePlaceholder: 'Enter preferred name',
  telephone: 'Telephone*',
  telephonePlaceholder: 'Enter telephone',
  pronouns: 'Pronouns*',
  pronounsPlaceholder: 'Select pronouns',
  country: 'Country*',
  countryPlaceholder: 'Select country',
  state: 'State*',
  statePlaceholder: 'Select state',
  postalCode: 'Postal code*',
  postalCodePlaceholder: 'Enter postal code',
  preferredAirport: 'Preferred airport*',
  preferredAirportPlaceholder: 'Enter preferred airport',
  nextButton: 'Next',
} as const;
