export const profileStrings = {
  title: 'Profile',
  personalInfo: 'Personal Information',
  notifications: 'Notifications',
  privacy: 'Privacy & Security',
  help: 'Help & Support',
  logout: 'Logout',
  // ProfileCard strings
  accountType: 'Account type :',
  preferredName: 'Preferred name',
  pronouns: 'Pronouns',
  email: 'Email',
  phoneNumber: 'Phone Number',
  address: 'Address',
  preferredAirport: 'Preferred airport',
  notSet: 'Not set',
  viewMore: 'View more',
  // ProfileSettings strings
  yourDocuments: 'Your documents',
  documentsSubtitle: 'Keep everything organized for your trip',
  settings: 'Settings',
  settingsSubtitle: 'Manage notifications, Change password',
  coordle: 'Coordle',
  about: 'About',
  signOut: 'Sign Out',
  deleteAccount: 'Delete Account',
  // Sign Out confirmation
  signOutConfirmTitle: 'Sign Out',
  signOutConfirmMessage: 'Are you sure you want to sign out of your account?',
  cancel: 'Cancel',
  signOutSuccess: 'Signed Out',
  signOutSuccessMessage: 'You have been successfully signed out.',
  signOutError: 'Error',
  signOutErrorMessage: 'Failed to sign out. Please try again.',
} as const;
